/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false` (hash: 323fb912484d6a15d203141660b138ca)
interface __BaseEnv_Env {
	DB: D1Database;
	FLARE_ENVIRONMENT: "development" | "preview" | "production";
	AUTH_ALLOWED_HOSTS: "localhost:5173" | "__SET_AUTH_ALLOWED_HOSTS__";
	AUTH_PROTOCOL: "http" | "https";
	BETTER_AUTH_SECRET: string;
}
declare namespace Cloudflare {
	interface DevelopmentEnv {
		DB: D1Database;
		FLARE_ENVIRONMENT: "development";
		AUTH_ALLOWED_HOSTS: "localhost:5173";
		AUTH_PROTOCOL: "http";
		BETTER_AUTH_SECRET: string;
	}
	interface PreviewEnv {
		DB: D1Database;
		FLARE_ENVIRONMENT: "preview";
		AUTH_ALLOWED_HOSTS: "__SET_AUTH_ALLOWED_HOSTS__";
		AUTH_PROTOCOL: "https";
		BETTER_AUTH_SECRET: string;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "FLARE_ENVIRONMENT" | "AUTH_ALLOWED_HOSTS" | "AUTH_PROTOCOL" | "BETTER_AUTH_SECRET">> {}
}
