/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=C:\Users\Jojo\Desktop\Projects\flare-stack\apps\web\wrangler.jsonc --include-runtime=false` (hash: 2c7a6e61b471846c7591e7656d6a65e9)
interface __BaseEnv_Env {
	DB: D1Database;
	FLARE_ENVIRONMENT: "development" | "preview" | "production";
	AUTH_ALLOWED_HOSTS: "localhost:5173" | "*-flare-reference-web.kojowap.workers.dev" | "flare-reference-web.kojowap.workers.dev";
	AUTH_PROTOCOL: "http" | "https";
	BETTER_AUTH_SECRET: string;
}
declare namespace Cloudflare {
	interface DevelopmentEnv {
		DB: D1Database;
		FLARE_ENVIRONMENT: "development";
		AUTH_ALLOWED_HOSTS: "localhost:5173";
		AUTH_PROTOCOL: "http";
		BETTER_AUTH_SECRET: string;
	}
	interface PreviewEnv {
		DB: D1Database;
		FLARE_ENVIRONMENT: "preview";
		AUTH_ALLOWED_HOSTS: "*-flare-reference-web.kojowap.workers.dev";
		AUTH_PROTOCOL: "https";
		BETTER_AUTH_SECRET: string;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "FLARE_ENVIRONMENT" | "AUTH_ALLOWED_HOSTS" | "AUTH_PROTOCOL" | "BETTER_AUTH_SECRET">> {}
}
